.TH ol.linux.bin 6 "June 2021" "ol.linux.bin" "Other Life Client"

.SH NAME
ol.linux.bin - Client for Other Life, a free MMORPG

.SH SYNOPSIS
.B ol.linux.bin
[
.I <other options> <config name>
]

.SH DESCRIPTION
Other Life is a free MMORPG (massively multi-player online role playing 
game).  Other-Life is based on the Eternal Lands free MMORPG.


.SH Web Resources

.TP
.I The main website for the game
https://www.other-life.com/

.TP
.I Game Forums
https://www.other-life.com/forums/

.TP
.I Client Source Code
https://github.com/pjbroad/other-life

.TP
.I Ubuntu & debian packages
https://twinmoons.org.uk/ol_linux_packages.html


.SH COPYRIGHT
Copyright (C) 2003-2021, Radu Privantu and Maura Privantu.
